KAFKA_TOPIC = 'CORK_ENV_WATERQUALITY_RIVER_YEARLY'
KAFKA_TOPIC_FINISH = 'CORK_ENV_WATERQUALITY_RIVER_FINISH_YEARLY'

ELASTICSEARCH_INDEX = 'cork_env_waterquality_river_yearly'

EXCEL_FILE = "Owenboy Subcatchment Chemistry EN.xlsx"

