KAFKA_TOPIC = 'THESS_ENV_HNMS_WIND_SPEED_MONTHLY'
KAFKA_TOPIC_FINISH = 'THESS_ENV_HNMS_WIND_SPEED_FINISH_MONTHLY'

ELASTICSEARCH_INDEX = 'thess_env_hnms_wind_speed_monthly'

EXCEL_FILE = "11196_WIND_SPEED_THESSALONIKI.xls"

