KAFKA_TOPIC = 'THESS_ENV_HNMS_FREQ_MONTHLY'
KAFKA_TOPIC_FINISH = 'THESS_ENV_HNMS_FREQ_FINISH_MONTHLY'

ELASTICSEARCH_INDEX = 'thess_env_hnms_wind_freq_monthly'

EXCEL_FILE = "11196_WIND_FREQ_THESSALONIKI.xls"

